### ISSUE TITLE
File masks no longer working under Linux

### ISSUE THREAD

**Issue by hsteinhaus** [diydrones/apm_planner#587] opened 2015-01-16 15:33 UTC
2.0.16 seems to conrain some change in the file name masks, e.g. for loading/saveing parameters in the full param list. 

The new mask ("*.param;*.txt") does no longer list any of the .param files in the directory. I guess this new mask is only matching on files named like "my_latest_params.param;*.txt". 

After removing "*.txt;", the .param files are shown again.

**Comment by billbonney** [comment] 2015-01-17 00:53
The problem is the mask should be separated by a space, not a semi-colon

**Comment by billbonney** [comment] 2015-01-17 01:03
Fixed in c2083245fe3cd9c37be13ee012c4451aec8e427c

**Closed** 2015-01-17 01:02 UTC
Labels: in progress

**Comment by hsteinhaus** [comment] 2015-01-17 08:16
The fix works perfectly here, thanks.
