### ISSUE TITLE
Roi visible in QGCMapWidget

### ISSUE THREAD

**Issue by wolkstein** [diydrones/apm_planner#602] opened 2015-02-05 02:15 UTC
hi,
i make "Set ROI" visible on Map. I am not sure if this make sense for other people. if yes i can create an pull request. https://github.com/wolkstein/apm_planner/commit/fe052d10858d13feaf4706b5d6abf1dbe7f27a53

this roi 2d item also work correct with "spline waypoints". see picture.

![roi](https://cloud.githubusercontent.com/assets/1617000/6053767/14df87d0-ace4-11e4-8690-623a6eafaf81.jpg)

/g
wolke

**Comment by wolkstein** [comment] 2015-02-06 01:03
hi,
today i spend a little bit more time to fix some problems on different loiter waypoints.

i noticed that loiter waypoints are displayed without a path. the path only was painted if spline waypoints are used behinf this loiter waypoints.

iattach an image which show some different loiter waypoints painted with the latest apmplanner2.
![differentloiterandland-orig](https://cloud.githubusercontent.com/assets/1617000/6072588/b570002a-ada3-11e4-95fd-5c30221c17fa.jpg)

after my changes loiter waypoints will painted in this way.
![differentloiterandland-fork](https://cloud.githubusercontent.com/assets/1617000/6072605/db38ac94-ada3-11e4-9355-387048f46575.jpg)

currently this changes https://github.com/wolkstein/apm_planner/commit/0ba9b74ce89948ab3d31b9b9638e865355f4ea76 are dependent to my first changes on roi. but it is also simply to make one pull request with only this bugfix on loiter waypoints.

/g
wolke

**Comment by billbonney** [comment] 2015-02-06 01:12
You can make one pull request. But in individual commits for easier review. Thx. :+1:

**Comment by billbonney** [comment] 2015-02-06 01:58
Duplicate of #519 and #379

**Comment by wolkstein** [comment] 2015-02-06 09:55
hi,

i create a first pull request https://github.com/diydrones/apm_planner/pull/604 which fix the not drawn path on some waypoints.
second i will create also an pull request for the roi fix.

**Comment by billbonney** [comment] 2015-02-06 18:12
closed with ac4c3cf

**Closed by billbonney** 2015-02-06 18:12 UTC
Labels: bug
