### ISSUE TITLE
Missing include in AP2DataPlotThread prevents build on Arch Linux

### ISSUE THREAD

**Issue by ZedGitHub** [diydrones/apm_planner#800] opened 2015-09-14 13:11 UTC
When trying to build the latest version on my Arch notebook it fails in AP2DataPlotThread.cc at line 168 
QDataStream packetstream(packet);
because QDataStream is not included.

Adding #include <QDataStream> in AP2DataPlotThread.h fixed the issue for me.

**Comment by billbonney** [comment] 2015-09-14 20:46
Duplicate of #781 . Build the qt55-wip branch for Qt5.5 builds. Thx

**Closed by billbonney** 2015-09-14 20:46 UTC
